### PR TITLE
Work on sending function

### PR DESCRIPTION
**Pull request by PMassicotte**
- I have finished some more sending functions (send paragraph, send function, send line, send all, etc.).
- Converted clear_all() to remove objects.

There are also some code change due to my lua formatter. If you prefer, I can desable it next time.

### CODE REVIEW

**Comment by PMassicotte** [comment]
I have tried to resolve conflicts directly on Github, but it seems I can not modify the code directly. 

I am out of town until Tuesday, I might be a bit slower to respond :)

**Comment by jalvesaq** [comment]
I'm not using a Lua formatter yet. I will install the one suggested by @she3o. We may standardize the whole code style at any moment, but it might be better when we are not editing so many files simultaneously to avoid creating too many conflicts in the next pull requests.

I invited you two to have access to this repository.

**Comment by jalvesaq** [comment]
I will try to resolve the conflicts...

**Comment by jalvesaq** [comment]
I'm sorry, but I can't resolve the conflicts. I can't distinguish what are real changes from what are style changes without becoming confused and making mistakes.

**Comment by PMassicotte** [comment]
No problems, I will do it tomorrow.

**Comment by PMassicotte** [comment]
Should be ok now!

**Comment by PMassicotte** [comment]
You might still see some formatting difference, my stylua uses stylua.toml in the project directory, so the changes should conform with the formatting defined for the project.

**Comment by jalvesaq** [comment]
OK! Thank you! I will change the stylua.toml...

**Pull request merged**
