### PR TITLE
feat: Introduce Test Suite

### PR DESCRIPTION
**Pull request by she3o**
This commit introduces a test suite to validate the functionality of the project. The changes include:

1. **.gitignore**: Added a new entry for the test directory to ensure that test-related artifacts are ignored.

2. **tests/README.md**: Added a README file for the test suite, providing instructions on how to run the tests using Neovim in headless mode. The README outlines the purpose of the test suite and the configuration options for running tests.

3. **tests/init.lua**: Added a custom configuration file for Neovim tests. This file sets up the runtime and package paths, loads essential plugins, and defines custom directories for configuration, data, state, and cache. The setup function ensures isolation of the test environment from the user's regular Neovim environment.

4. **tests/r/utils_spec.lua**: Introduced test cases for utility functions. The `ensure_directory_exists` function is tested for both successful directory creation and handling errors during creation. Note: The test case attempting to create a directory in a protected Unix directory is currently commented out because it fails on my machine. I don't know why.

5. **tests/run**: Added a script to simplify running the Neovim test suite. The script sets the test directory and init.lua and then executes Neovim in headless mode with the PlenaryBusted test runner.

The test suite aims to enhance project reliability and facilitate future development by automating the validation process.

### CODE REVIEW

**Comment by jalvesaq** [comment]
`ensure_directory_exists` is testing `vim.fn.isdirectory()` too. Please, see: https://github.com/jalvesaq/tmp-R-Nvim/issues/1#issuecomment-1920432018

**Comment by jalvesaq** [comment]
It's great to have a test suite. I should have created one 14 years ago.

**Comment by jalvesaq** [comment]
I fixed the test, but I don't know how to push the commit to this pull request. I'm trying to learn how to use lazygit and I created a branch instead of pushing the change to this pull request:

https://github.com/jalvesaq/tmp-R-Nvim/tree/she3o-add-testing

**Comment by jalvesaq** [comment]
How to use selene? Could you, please, point to an online example? Currently, I'm using:
- 'folke/neodev.nvim'
- 'ray-x/lsp_signature.nvim'
- 'neovim/nvim-lspconfig' and `require('lspconfig')['lua_ls'].setup`

**Comment by PMassicotte** [comment]
Are you using Mason? If so, you can install it with `MasonInstall selene`

**Comment by jalvesaq** [comment]
Not using mason, but I can if necessary. I installed selene manually. My problem is how to integrate it with lsp, although my setup seems complete to me because I get completion, diagnostic messages, renaming of variables, etc...

**Comment by jalvesaq** [comment]
It will be useful to have selene diagnostics too. Running it manually I see a warning about hexadecimal escape sequences being invalid (although they are working in Neovim).

**Comment by jalvesaq** [comment]
I merged this pull request and later fixed the test on the main branch.

**Comment by PMassicotte** [comment]
We could also a Github Action that will run a linter on push to make sure that all formatting is good. I can setup it if needed.

**Comment by PMassicotte** [comment]
Great. I will be back to office tomorrow and will work on it.

**Pull request merged**
