### PR TITLE
Optimize and refactor Lua scripts

### PR DESCRIPTION
**Pull request by she3o**
This commit optimizes our Lua scripts by leveraging the `vim.loop` API over `vim.fn` for certain operations, specifically for platform detection using `vim.loop.os_uname().sysname` to replace `vim.fn.has("win32")`. The `vim.loop` API interfaces directly with libuv, the high-performance asynchronous I/O library used by Neovim. This can significantly enhance performance, especially in I/O-bound tasks or system calls.

Key benefits and changes include:

1. Improved performance: `vim.loop`'s non-blocking nature reduces delays in script execution, leading to a smoother user experience.

2. Utility module introduction: `lua/r/utils.lua` centralizes common functions, including those benefiting from `vim.loop`, like `ensure_directory_exists`, which optimizes directory handling.

3. Standardized path handling: The utility functions ensure consistent and efficient path normalization and checks across different operating systems.

4. Fix typo in R/nvimcom/src/nvimcom.c

### CODE REVIEW

**Comment by jalvesaq** [comment]
Great!

**Comment by jalvesaq** [comment]
After merging the pull request, I'm getting this error when editing any R file:

```
tmp-R-Nvim/lua/r/config.lua:204: attempt to index upvalue 'utils' (a nil value)
```

Note: I pushed some changes, so you have to pull them to get the correct line number. The line is:

```lua
  utils.ensure_directory_exists(config.compldir)
```

**Comment by jalvesaq** [comment]
I'm using Neovim built from source and it's up to date.

**Comment by jalvesaq** [comment]
vim.loop is deprecated:
https://neovim.io/doc/user/deprecated.html#vim.loop

**Comment by jalvesaq** [comment]
There was an error in the `require` command. I fixed it.

**Comment by jalvesaq** [comment]
I was commenting on the wrong issue: #1

**Comment by jalvesaq** [comment]
`vim.loop` was deprecated, but still works.
https://github.com/neovim/neovim/pull/22846

**Comment by she3o** [comment]
> vim.loop was deprecated, but still works.

They haven't updated the docs yet. So I assumed it's best practice to call loop :smiling_face_with_tear:

I will replace `vim.loop` with `vim.uv` in the next commit

**Pull request merged**
